-- EWOH standalone schema rollback
-- DESTRUCTIVE: drops every table created by standalone_001_schema.sql.
-- Shared cluster roles (anon, authenticated, service_role) are intentionally retained.
SELECT set_config('search_path', 'public, pg_temp', false);

DROP TABLE IF EXISTS public.ewoh_asset_package CASCADE;
DROP TABLE IF EXISTS public.ewoh_factory_profile CASCADE;
DROP TABLE IF EXISTS public.ewoh_factory_template CASCADE;
DROP TABLE IF EXISTS public.ewoh_audit_log CASCADE;
DROP TABLE IF EXISTS public.ewoh_notification CASCADE;
DROP TABLE IF EXISTS public.ewoh_knowledge_entry CASCADE;
DROP TABLE IF EXISTS public.ewoh_knowledge_base CASCADE;
DROP TABLE IF EXISTS public.ewoh_system_config CASCADE;
DROP TABLE IF EXISTS public.ewoh_world_delta_log CASCADE;
DROP TABLE IF EXISTS public.ewoh_world_snapshot CASCADE;
DROP TABLE IF EXISTS public.ewoh_event_subscription CASCADE;
DROP TABLE IF EXISTS public.ewoh_event_action CASCADE;
DROP TABLE IF EXISTS public.ewoh_event_rule CASCADE;
DROP TABLE IF EXISTS public.ewoh_control_result CASCADE;
DROP TABLE IF EXISTS public.ewoh_control_command CASCADE;
DROP TABLE IF EXISTS public.ewoh_control_request CASCADE;
DROP TABLE IF EXISTS public.ewoh_resource_binding CASCADE;
DROP TABLE IF EXISTS public.ewoh_resource_preorder CASCADE;
DROP TABLE IF EXISTS public.ewoh_schedule_assignment CASCADE;
DROP TABLE IF EXISTS public.ewoh_schedule_task_step CASCADE;
DROP TABLE IF EXISTS public.ewoh_schedule_task CASCADE;
DROP TABLE IF EXISTS public.ewoh_task_skill_req CASCADE;
DROP TABLE IF EXISTS public.ewoh_task_step CASCADE;
DROP TABLE IF EXISTS public.ewoh_task_template CASCADE;
DROP TABLE IF EXISTS public.ewoh_workstation_relation CASCADE;
DROP TABLE IF EXISTS public.ewoh_workstation_skill CASCADE;
DROP TABLE IF EXISTS public.ewoh_workstation_person CASCADE;
DROP TABLE IF EXISTS public.ewoh_workstation_device CASCADE;
DROP TABLE IF EXISTS public.ewoh_workstation CASCADE;
DROP TABLE IF EXISTS public.ewoh_model_binding CASCADE;
DROP TABLE IF EXISTS public.ewoh_model_asset CASCADE;
DROP TABLE IF EXISTS public.ewoh_spatial_hierarchy CASCADE;
DROP TABLE IF EXISTS public.ewoh_spatial_relation CASCADE;
DROP TABLE IF EXISTS public.ewoh_device_capability CASCADE;
DROP TABLE IF EXISTS public.ewoh_person_role CASCADE;
DROP TABLE IF EXISTS public.ewoh_role CASCADE;
DROP TABLE IF EXISTS public.ewoh_skill CASCADE;
DROP TABLE IF EXISTS public.ewoh_person_skill CASCADE;
DROP TABLE IF EXISTS public.ewoh_world_state CASCADE;
DROP TABLE IF EXISTS public.ewoh_topology CASCADE;
DROP TABLE IF EXISTS public.ewoh_telemetry CASCADE;
DROP TABLE IF EXISTS public.ewoh_spatial_entity CASCADE;
DROP TABLE IF EXISTS public.ewoh_scheduler_config CASCADE;
DROP TABLE IF EXISTS public.ewoh_schedule_plan CASCADE;
DROP TABLE IF EXISTS public.ewoh_schedule_audit CASCADE;
DROP TABLE IF EXISTS public.ewoh_production_task CASCADE;
DROP TABLE IF EXISTS public.ewoh_personnel CASCADE;
DROP TABLE IF EXISTS public.ewoh_organization CASCADE;
DROP TABLE IF EXISTS public.ewoh_model_registry CASCADE;
DROP TABLE IF EXISTS public.ewoh_event_chain CASCADE;
DROP TABLE IF EXISTS public.ewoh_event CASCADE;
DROP TABLE IF EXISTS public.ewoh_environment CASCADE;
DROP TABLE IF EXISTS public.ewoh_device_config CASCADE;
DROP TABLE IF EXISTS public.ewoh_device_binding CASCADE;
DROP TABLE IF EXISTS public.ewoh_device CASCADE;
DROP TABLE IF EXISTS public.ewoh_ai_suggestion CASCADE;
DROP FUNCTION IF EXISTS public.ewoh_append_audit_log(uuid, text, text, text, text, jsonb, jsonb, text, text, text, boolean, text);
DROP FUNCTION IF EXISTS public.ewoh_org_visible(uuid);
