// Generated by scripts/gen-openapi.js from openapi/work-orchestration.yaml. DO NOT EDIT.

export interface paths {
    "/api/work/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Work orchestration overview
         * @description Phase, critical path, counts, gate statuses, and artifact conflicts.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Overview */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkOverview"];
                    };
                };
                Unauthorized: components["responses"]["Unauthorized"];
                Forbidden: components["responses"]["Forbidden"];
                InternalError: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/work/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Canonical work graph
         * @description Versioned graph generated from authoritative repository artifacts.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Work graph */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkGraph"];
                    };
                };
                Unauthorized: components["responses"]["Unauthorized"];
                Forbidden: components["responses"]["Forbidden"];
                InternalError: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/work/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List work items */
        get: {
            parameters: {
                query?: {
                    status?: string;
                    type?: string;
                    owner?: string;
                    wave?: string;
                    q?: string;
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Work items */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkItem"][];
                    };
                };
                Unauthorized: components["responses"]["Unauthorized"];
                Forbidden: components["responses"]["Forbidden"];
                InternalError: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/work/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List evidence records */
        get: {
            parameters: {
                query?: {
                    kind?: string;
                    result?: string;
                    q?: string;
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Evidence records */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkEvidence"][];
                    };
                };
                Unauthorized: components["responses"]["Unauthorized"];
                Forbidden: components["responses"]["Forbidden"];
                InternalError: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/work/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List orchestration actors */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Actors */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkActor"][];
                    };
                };
                Unauthorized: components["responses"]["Unauthorized"];
                Forbidden: components["responses"]["Forbidden"];
                InternalError: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/work/evidence/{id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Preview evidence file content
         * @description Returns a bounded text preview of an evidence artifact.
         */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Evidence content preview */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EvidenceContent"];
                    };
                };
                Unauthorized: components["responses"]["Unauthorized"];
                Forbidden: components["responses"]["Forbidden"];
                NotFound: components["responses"]["NotFound"];
                InternalError: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/work/gates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gate decisions
         * @description Calculated gate statuses with human decisions separated from rule results.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Gate decisions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkGate"][];
                    };
                };
                Unauthorized: components["responses"]["Unauthorized"];
                Forbidden: components["responses"]["Forbidden"];
                InternalError: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/work/risks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List orchestration risks */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Risks */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkRisk"][];
                    };
                };
                Unauthorized: components["responses"]["Unauthorized"];
                Forbidden: components["responses"]["Forbidden"];
                InternalError: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/work/gates/batch-decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record gate decisions in batch
         * @description Writes human decisions for multiple gates in one audited file update.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BatchGateDecisionRequest"];
                };
            };
            responses: {
                /** @description Batch result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                Unauthorized: components["responses"]["Unauthorized"];
                Forbidden: components["responses"]["Forbidden"];
                NotFound: components["responses"]["NotFound"];
                InternalError: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/work/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List orchestration resources and locks */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Resources */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkResource"][];
                    };
                };
                Unauthorized: components["responses"]["Unauthorized"];
                Forbidden: components["responses"]["Forbidden"];
                InternalError: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/work/handoffs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List handoffs */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Handoffs */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkHandoff"][];
                    };
                };
                Unauthorized: components["responses"]["Unauthorized"];
                Forbidden: components["responses"]["Forbidden"];
                InternalError: components["responses"]["InternalError"];
            };
        };
        put?: never;
        /** Create a handoff record */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["HandoffRequest"];
                };
            };
            responses: {
                /** @description Created handoff */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkHandoff"];
                    };
                };
                Unauthorized: components["responses"]["Unauthorized"];
                Forbidden: components["responses"]["Forbidden"];
                InternalError: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/work/handoffs/{id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Transition handoff state
         * @description Accepts, rejects, or closes a handoff record and persists the change to its markdown file.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["HandoffStateRequest"];
                };
            };
            responses: {
                /** @description Updated handoff state */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                Unauthorized: components["responses"]["Unauthorized"];
                Forbidden: components["responses"]["Forbidden"];
                NotFound: components["responses"]["NotFound"];
                InternalError: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/work/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Final 6 asset catalog
         * @description C8 asset catalog generated from catalog/ manifests.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Asset catalog */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkCatalog"];
                    };
                };
                Unauthorized: components["responses"]["Unauthorized"];
                Forbidden: components["responses"]["Forbidden"];
                InternalError: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/work/site-readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List factory site-readiness reports
         * @description Evaluates catalog/factory-sites reports with the site readiness rules.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Site readiness summaries */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SiteReadinessSummary"][];
                    };
                };
                Unauthorized: components["responses"]["Unauthorized"];
                Forbidden: components["responses"]["Forbidden"];
                InternalError: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/work/git-sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GitHub Issue/PR sync plan
         * @description Offline-first mapping between work graph items and GitHub tracking records.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Git sync plan */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GitSyncPlan"];
                    };
                };
                Unauthorized: components["responses"]["Unauthorized"];
                Forbidden: components["responses"]["Forbidden"];
                InternalError: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/work/git-sync/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply offline GitHub Issue/PR sync plan (approval-gated)
         * @description Applies the offline Git sync plan to GitHub. Requires preceding human approval (`approved=true`) and an idempotency key; repeated submission with the same key returns the original result. Live GitHub mutation additionally requires EWOH_GIT_SYNC_ENABLED/GITHUB_TOKEN/ EWOH_GIT_SYNC_APPROVED on the server.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["GitSyncApplyRequest"];
                };
            };
            responses: {
                /** @description Live sync result */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
                BadRequest: components["responses"]["BadRequest"];
                Unauthorized: components["responses"]["Unauthorized"];
                Forbidden: components["responses"]["Forbidden"];
                Conflict: components["responses"]["Conflict"];
                InternalError: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/work/resources/{id}/lock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Acquire a resource lock */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ResourceLockRequest"];
                };
            };
            responses: {
                /** @description Lock record */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ResourceLockRecord"];
                    };
                };
                Unauthorized: components["responses"]["Unauthorized"];
                Forbidden: components["responses"]["Forbidden"];
                NotFound: components["responses"]["NotFound"];
                Conflict: components["responses"]["Conflict"];
                InternalError: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/work/resources/{id}/renew": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Renew a resource lock
         * @description Extends the lease on an active resource lock held by the current holder. Returns the updated lock record with a bumped version (optimistic lock).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /**
                         * Format: date-time
                         * @description New expiry for the lock lease
                         */
                        expiresAt?: string;
                    };
                };
            };
            responses: {
                /** @description Updated lock record */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ResourceLockRecord"];
                    };
                };
                Unauthorized: components["responses"]["Unauthorized"];
                Forbidden: components["responses"]["Forbidden"];
                NotFound: components["responses"]["NotFound"];
                InternalError: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/work/resources/{id}/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Release a resource lock */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Release result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ResourceReleaseResult"];
                    };
                };
                Unauthorized: components["responses"]["Unauthorized"];
                Forbidden: components["responses"]["Forbidden"];
                NotFound: components["responses"]["NotFound"];
                InternalError: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/work/resources/recover-expired": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recover expired resource locks
         * @description Releases all active resource locks whose lease has expired (e.g. a holder crashed without releasing). Returns the number of locks recovered.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Number of expired locks recovered */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description Count of expired locks released */
                            recovered?: number;
                        };
                    };
                };
                Unauthorized: components["responses"]["Unauthorized"];
                Forbidden: components["responses"]["Forbidden"];
                NotFound: components["responses"]["NotFound"];
                InternalError: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/work/gates/{id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record a human gate decision */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["GateDecisionRequest"];
                };
            };
            responses: {
                /** @description Recorded decision */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GateDecisionRecord"];
                    };
                };
                Unauthorized: components["responses"]["Unauthorized"];
                Forbidden: components["responses"]["Forbidden"];
                NotFound: components["responses"]["NotFound"];
                InternalError: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/work/gates/{id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke a human gate decision
         * @description Removes the current human decision for a gate. If history contains an earlier decision for the gate it is restored (rolled back), otherwise the gate returns to no-decision state. The revocation is appended to the history as an action='revoked' audit record.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["GateRevokeRequest"];
                };
            };
            responses: {
                /** @description Revocation result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GateRevokeResult"];
                    };
                };
                Unauthorized: components["responses"]["Unauthorized"];
                Forbidden: components["responses"]["Forbidden"];
                NotFound: components["responses"]["NotFound"];
                BadRequest: components["responses"]["BadRequest"];
                InternalError: components["responses"]["InternalError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/work/gates/{id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gate decision history
         * @description Returns the full decision/revocation history for a gate.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Gate history */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GateHistoryRecord"][];
                    };
                };
                Unauthorized: components["responses"]["Unauthorized"];
                Forbidden: components["responses"]["Forbidden"];
                NotFound: components["responses"]["NotFound"];
                InternalError: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/work/items/{id}/blocked-reason": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Explain why a work item is blocked
         * @description Resolves a work item's predecessor dependencies (blocking/depends edges) and gate status, returning a natural-language Chinese explanation of why the item is currently blocked.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Blocked reason */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BlockedReason"];
                    };
                };
                Unauthorized: components["responses"]["Unauthorized"];
                Forbidden: components["responses"]["Forbidden"];
                NotFound: components["responses"]["NotFound"];
                InternalError: components["responses"]["InternalError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        WorkOverview: {
            [key: string]: unknown;
        };
        WorkGraph: {
            [key: string]: unknown;
        };
        WorkItem: {
            [key: string]: unknown;
        };
        WorkEdge: {
            [key: string]: unknown;
        };
        WorkActor: {
            [key: string]: unknown;
        };
        WorkEvidence: {
            evidenceId: string;
            workItemId?: string;
            title?: string;
            kind: string;
            path: string;
            checksum?: string;
            result?: string;
            branch?: string;
            commitSha?: string;
            buildVersion?: string;
            envFingerprint?: string;
            dependencyVersion?: string;
            testTime?: string;
            verifier?: string;
            expiresAt?: string;
            /** @enum {string} */
            status?: "valid" | "stale" | "expired" | "unbound";
            staleReason?: string;
        } & {
            [key: string]: unknown;
        };
        EvidenceContent: {
            [key: string]: unknown;
        };
        WorkGate: {
            [key: string]: unknown;
        };
        WorkRisk: {
            [key: string]: unknown;
        };
        WorkResource: {
            [key: string]: unknown;
        };
        WorkHandoff: {
            [key: string]: unknown;
        };
        WorkCatalog: {
            [key: string]: unknown;
        };
        GitSyncPlan: {
            [key: string]: unknown;
        };
        GitSyncApplyRequest: {
            /** @description Client-generated key; repeated submission returns the original result. */
            idempotencyKey: string;
            /** @description Human approval gate; must be true to mutate GitHub. */
            approved: boolean;
            /** @description Optional justification recorded in the audit trail. */
            reason?: string;
            /** @description Optional acting user identity recorded in the audit trail. */
            actor?: string;
        } & {
            [key: string]: unknown;
        };
        SiteReadinessSummary: {
            [key: string]: unknown;
        };
        ResourceLockRequest: {
            purpose?: string;
            expiresAt?: string;
            confirm?: boolean;
        } & {
            [key: string]: unknown;
        };
        ResourceLockRecord: {
            [key: string]: unknown;
        };
        ResourceReleaseResult: {
            [key: string]: unknown;
        };
        HandoffRequest: {
            [key: string]: unknown;
        };
        HandoffStateRequest: {
            /** @enum {string} */
            status: "accepted" | "rejected" | "closed";
            reason?: string;
        } & {
            [key: string]: unknown;
        };
        GateDecisionRequest: {
            /** @enum {string} */
            decision: "approved" | "rejected" | "conditional";
            conditions?: string[];
        } & {
            [key: string]: unknown;
        };
        BatchGateDecisionRequest: {
            gateIds: string[];
            /** @enum {string} */
            decision: "approved" | "rejected" | "conditional";
            conditions?: string[];
        } & {
            [key: string]: unknown;
        };
        GateDecisionRecord: {
            [key: string]: unknown;
        };
        GateRevokeRequest: {
            /** @description Optional justification recorded in the audit trail. */
            reason?: string;
        } & {
            [key: string]: unknown;
        };
        GateRevokeResult: {
            gateId: string;
            revoked: boolean;
            revokedAt: string;
            revokedBy: string;
            reason?: string;
            restored?: ({
                gateId?: string;
                decision?: string;
            } & {
                [key: string]: unknown;
            }) | null;
        } & {
            [key: string]: unknown;
        };
        GateHistoryRecord: {
            gateId: string;
            /** @enum {string} */
            decision: "approved" | "rejected" | "conditional";
            approver?: string;
            decidedAt?: string;
            conditions?: string[];
            /** @enum {string} */
            action?: "decision" | "revoked";
            reason?: string;
            revokedAt?: string;
            revokedBy?: string;
        } & {
            [key: string]: unknown;
        };
        BlockedReason: {
            itemId: string;
            blocked: boolean;
            explanation: string;
        } & {
            [key: string]: unknown;
        };
    };
    responses: {
        /** @description Unauthorized */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Forbidden */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Conflict */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Internal server error */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
