allowBuilds:
  '@nestjs/core': true
  core-js: true
  esbuild: true
  protobufjs: true
overrides:
  '@tiptap/core': ^3.31.3
  '@tiptap/pm': ^3.31.3
  prosemirror-view: ^1.42.4
  fast-uri: ^3.1.8
  js-yaml: ^4.3.2
  nanoid@3: ^3.3.19
  multer: ^2.4.0
