apiVersion: v1
kind: Secret
metadata:
  name: ewoh-api-secret
  namespace: ewoh
type: Opaque
stringData:
  DATABASE_URL: "postgresql://ewoh_api:REPLACE_WITH_URI_SAFE_RUNTIME_PASSWORD@postgres.example:5432/ewoh"
  REDIS_URL: "redis://redis.example:6379"
  JWT_SECRET: "REPLACE_WITH_A_RANDOM_SECRET_OF_AT_LEAST_32_CHARACTERS"
  OBJECT_STORAGE_ACCESS_KEY: ""
  OBJECT_STORAGE_SECRET_KEY: ""
