/** Stateful database double only: canonical, execution, task, outbox and request
 * transaction services are real. Transactions serialize at database scope here;
 * PostgreSQL row-lock contention is covered by the separate real-PG suite. */
import { randomUUID } from 'node:crypto';
import { getTableColumns, getTableName, type SQL, type Table } from 'drizzle-orm';
import { PgDialect } from 'drizzle-orm/pg-core';
import {
  ewohAssignmentEvent, ewohDevice, ewohProductionTask, ewohSchedulePlan,
  ewohSchedulingExecution, ewohSchedulingFeedback, ewohSchedulingPlanAssignment, ewohOutbox,
} from '@server/database/schema';
import { SchedulingFeedbackService } from '../scheduling-feedback.service';
import { ExecutionReceiptApplicationService } from '../execution-receipt-application.service';
import { ExecutionService } from '../execution.service';
import { OutboxService } from '../outbox.service';
import { TaskService } from '../../task/task.service';
import { RequestDatabaseContext } from '../../../database/request-database-context';
import type { OrgContext } from '../../shared/org-context.interceptor';

export const RECEIPT_TASK_ID = '9f1c4a0e-5d0b-4f3a-9c1e-7d3b9a6f0a11';
type Row = Record<string, any>;
export interface ReceiptHarnessState {
  plans: Row[]; assignments: Row[]; tasks: Row[]; executions: Row[]; feedback: Row[];
  devices: Row[]; events: Row[]; taskAudit: Row[]; outbox: Row[];
}
const tableKeys = new Map<Table, keyof ReceiptHarnessState>([
  [ewohSchedulePlan, 'plans'], [ewohSchedulingPlanAssignment, 'assignments'],
  [ewohProductionTask, 'tasks'], [ewohSchedulingExecution, 'executions'],
  [ewohSchedulingFeedback, 'feedback'], [ewohAssignmentEvent, 'events'],
  [ewohDevice, 'devices'], [ewohOutbox, 'outbox'],

]);
// Native structuredClone returns Date objects from outside Jest's VM realm.
// Clone recursively here so instanceof Date has the same semantics as ORM rows.
function clone<T>(value: T): T {
  if (value instanceof Date) return new Date(value.getTime()) as T;
  if (Array.isArray(value)) return value.map(clone) as T;
  if (value && typeof value === 'object') return Object.fromEntries(Object.entries(value).map(([key, item]) => [key, clone(item)])) as T;
  return value;
}
const dialect = new PgDialect();
const equivalent = (a: unknown, b: unknown) => a instanceof Date || b instanceof Date
  ? new Date(a as string).getTime() === new Date(b as string).getTime() : a === b;

/** Interpret the SQL generated by Drizzle, fail loudly for unsupported predicates.
 * This prevents silently ignoring a missing AND or tenant predicate in a test. */
function matches(table: Table, row: Row, predicate?: SQL): boolean {
  if (!predicate) return true;
  const { sql, params } = dialect.sqlToQuery(predicate);
  const fields = getTableColumns(table);
  const names = new Map(Object.entries(fields).map(([key, col]) => [col.name, key]));
  const tokens = sql.match(/"[^"]+"\."[^"]+"|\$\d+|is\s+not\s+null|is\s+null|and|or|=|\(|\)/gi) ?? [];
  let i = 0;
  const atom = (): boolean => {
    if (tokens[i] === '(') {
      i++; const value = disjunction();
      if (tokens[i++] !== ')') throw new Error(`Unbalanced predicate: ${sql}`);
      return value;
    }
    const ref = tokens[i++]; const col = /\."([^"]+)"$/.exec(ref ?? '')?.[1];
    const key = col && names.get(col); if (!key) throw new Error(`Unsupported column: ${sql}`);
    const op = tokens[i++]?.toLowerCase();
    if (op === 'is null') return row[key] == null;
    if (op === 'is not null') return row[key] != null;
    if (op !== '=') throw new Error(`Unsupported operator: ${sql}`);
    const parameter = /^\$(\d+)$/.exec(tokens[i++] ?? '');
    if (!parameter) throw new Error(`Unsupported value: ${sql}`);
    return equivalent(row[key], params[Number(parameter[1]) - 1]);
  };
  const conjunction = (): boolean => {
    let value = atom(); while (tokens[i]?.toLowerCase() === 'and') { i++; const next = atom(); value = value && next; } return value;
  };
  const disjunction = (): boolean => {
    let value = conjunction(); while (tokens[i]?.toLowerCase() === 'or') { i++; const next = conjunction(); value = value || next; } return value;
  };
  const result = disjunction();
  if (i !== tokens.length) throw new Error(`Unsupported predicate: ${sql}`);
  return result;
}

export function makeCanonicalReceiptHarness(seed: {
  planStatus?: string; assignmentStatus?: string; taskStatus?: string; personId?: string; device?: boolean;
  taskId?: string; assignmentId?: string; planId?: string; executionStatus?: string;
  executionSource?: string; failOutbox?: boolean;
  /**
   * 登录账号 id（身份域）。与 `personId`（人员域）刻意分离——两者相同会让
   * "本人可报"测试在没有绑定的情况下也通过。
   */
  actorUserId?: string;
} = {}) {
  const planId = seed.planId ?? 'PLAN-RECEIPT-1';
  /**
   * 默认 harness 代表"已绑定的本人"：assignment.personId 与账号绑定一致。
   * 需要验证越权/未绑定时，用例显式覆盖 personId 或不传 actor.personId。
   */
  const boundPersonId = seed.personId ?? 'worker-1';
  const assigneeUserId = seed.actorUserId ?? 'acct-worker-1';
  const assignmentId = seed.assignmentId ?? 'ASG-RECEIPT-1';
  const taskId = seed.taskId ?? RECEIPT_TASK_ID;
  const deviceId = seed.device === false ? null : '00000000-0000-4000-8000-000000000021';
  const start = new Date('2026-08-16T08:00:00.000Z');
  const end = new Date('2026-08-16T08:30:00.000Z');
  const state: ReceiptHarnessState = {
    plans: [{ id: randomUUID(), planId, orgId: 'org1', status: seed.planStatus ?? 'approved', isShadow: false,
      createdBy: 'planner-1', confirmedBy: 'approver-2', confirmedAt: new Date('2026-08-15T08:00:00Z'), metricsJson: {} }],
    assignments: [{ id: randomUUID(), assignmentId, planId, taskId, orgId: 'org1', personId: boundPersonId, deviceId, stationId: 's1',
      status: seed.assignmentStatus ?? 'dispatched', version: 1, plannedStart: start, plannedEnd: end, etaSeconds: 120 }],
    tasks: [{ id: taskId, orgId: 'org1', status: seed.taskStatus ?? 'dispatched', source: 'real' }],
    executions: [{ id: randomUUID(), executionId: `EXEC-${assignmentId}`, orgId: 'org1', runId: 'RUN-1', planId, assignmentId, taskId,
      deviceId, personId: boundPersonId, stationId: 's1', status: seed.executionStatus ?? 'DISPATCHED', source: seed.executionSource ?? 'dispatch', actualStartAt: null, actualEndAt: null,
      actualTravelMs: null, actualWaitingMs: null, actualDistanceM: null, plannedStartAt: start, plannedEndAt: end, plannedTravelMs: 120000,
      plannedDistanceM: null, plannedWaitingMs: null, deviationType: null, deviationReason: null, snapshotVersion: 'WS-1', policyVersion: 1, solverVersion: 'test', createdAt: start, updatedAt: start }],
    feedback: [], devices: deviceId ? [{ id: deviceId, orgId: 'org1', sourceType: 'real' }] : [], events: [], taskAudit: [], outbox: [],
  };
  const trace: Array<{ op: string; table?: string; mode?: string; sql?: string; params?: unknown[] }> = [];
  const faults: { insert?: Table; update?: Table; casMiss?: Table; audit?: boolean } = seed.failOutbox ? { insert: ewohOutbox } : {};
  const rows = (table: Table): Row[] => {
    const key = tableKeys.get(table); if (!key) throw new Error(`Unsupported table: ${getTableName(table)}`); return state[key];
  };
  let active = false;
  const assertTransaction = () => { if (!active) throw new Error('Receipt database access outside transaction'); };
  const once = (run: () => Row[]): any => {
    let result: Row[] | undefined;
    const q: any = { returning: () => q, onConflictDoNothing: () => q,
      then: (resolve: (v: Row[]) => unknown, reject: (e: unknown) => unknown) => {
        try { if (!result) result = run(); return Promise.resolve(clone(result)).then(resolve, reject); }
        catch (error) { return Promise.reject(error).then(resolve, reject); }
      } };
    return q;
  };
  const connection: any = {
    select: () => ({ from: (table: Table) => {
      let predicate: SQL | undefined; let limit = Infinity; let mode: string | undefined;
      const q: any = { where: (p: SQL) => { predicate = p; return q; }, limit: (n: number) => { limit = n; return q; }, orderBy: () => q,
        for: (m: string) => { mode = m; return q; },
        then: (resolve: (v: Row[]) => unknown) => {
          assertTransaction(); trace.push({ op: 'select', table: getTableName(table), mode, ...(predicate ? dialect.sqlToQuery(predicate) : {}) });
          return Promise.resolve(clone(rows(table).filter(r => matches(table, r, predicate)).slice(0, limit))).then(resolve);
        } };
      return q;
    }}),
    insert: (table: Table) => ({ values: (value: Row | Row[]) => once(() => {
      assertTransaction(); trace.push({ op: 'insert', table: getTableName(table) });
      if (faults.insert === table) throw new Error(`injected insert failure: ${getTableName(table)}`);
      const inserted: Row[] = [];
      for (const input of Array.isArray(value) ? value : [value]) {
        if (table === ewohSchedulingExecution && rows(table).some(r => r.orgId === input.orgId && r.assignmentId === input.assignmentId)) continue;
        const row = { id: randomUUID(), createdAt: new Date(), updatedAt: new Date(), sequence: state.outbox.length + 1, ...clone(input) };
        rows(table).push(row); inserted.push(row);
      }
      return inserted;
    }) }),
    update: (table: Table) => ({ set: (patch: Row) => ({ where: (predicate: SQL) => once(() => {
      assertTransaction(); trace.push({ op: 'update', table: getTableName(table), ...dialect.sqlToQuery(predicate) });
      if (faults.update === table) throw new Error(`injected update failure: ${getTableName(table)}`);
      if (faults.casMiss === table) return [];
      const hit = rows(table).filter(r => matches(table, r, predicate));
      for (const row of hit) for (const [key, value] of Object.entries(patch)) {
        if (value?.queryChunks) {
          if (!/\+ 1$/.test(dialect.sqlToQuery(value).sql)) throw new Error('Unsupported update expression');
          row[key] = Number(row[key]) + 1;
        } else row[key] = clone(value);
      }
      return hit;
    }) }) }),
    execute: async (query: SQL) => { assertTransaction(); trace.push({ op: 'execute', ...dialect.sqlToQuery(query) }); return []; },
  };
  let queue = Promise.resolve();
  const root: any = { ...connection, transaction: async (operation: (tx: unknown) => Promise<unknown>) => {
    const prior = queue; let release!: () => void; queue = new Promise<void>(resolve => { release = resolve; });
    await prior; const snapshot = clone(state); active = true; trace.push({ op: 'begin' });
    try { const result = await operation(connection); trace.push({ op: 'commit' }); return result; }
    catch (error) { Object.assign(state, snapshot); trace.push({ op: 'rollback' }); throw error; }
    finally { active = false; release(); }
  }};
  const requestDatabaseContext = new RequestDatabaseContext(root);
  const db = requestDatabaseContext.database;
  const outbox = new OutboxService(db as never);
  const executionService = new ExecutionService(db as never, outbox, { recordExecutionTransition: jest.fn() } as never);
  const taskService = new TaskService(db as never, { appendAuditLog: async (entry: Row) => {
    assertTransaction(); if (faults.audit) throw new Error('injected audit failure'); state.taskAudit.push(clone(entry));
  }} as never);
  const canonical = new ExecutionReceiptApplicationService(db as never, requestDatabaseContext, executionService, taskService);
  const feedback = new SchedulingFeedbackService(db as never, requestDatabaseContext, undefined, undefined, canonical);
  /**
   * 操作者上下文（2026-09-10 修正）。
   *
   * 旧实现把 `userId` 直接设成 `seed.personId`——即用登录账号冒充业务人员，
   * 恰好绕过了"两个标识空间被直接比较"的真实缺陷，于是测试全绿而现场 worker
   * 永远无法回执。现在按真实形状构造：登录账号 id 与人员 id 分离，人员身份
   * 只能经 `personId`（现实中来自签名令牌里的账号↔人员绑定）表达。
   */
  const actor: OrgContext = {
    userId: assigneeUserId,
    primaryOrgId: 'org1',
    personId: boundPersonId,
  };
  return { canonical, feedback, state, actor, db, planId, assignmentId, taskId, deviceId, trace, faults, taskService, requestDatabaseContext, executionService };
}
