/**
 * gen-openapi.js
 *
 * Reproducible TypeScript contract generation from the hand-maintained OpenAPI
 * specs, plus a no-drift gate.
 *
 *   node scripts/gen-openapi.js            -> regenerate committed outputs
 *   node scripts/gen-openapi.js --check    -> regenerate into a temp dir and
 *                                             diff against committed outputs;
 *                                             exits non-zero on any drift so CI
 *                                             can fail before a stale contract
 *                                             is merged.
 *
 * Generator: openapi-typescript (pure, type-only, no runtime). Pinned as a
 * devDependency so CI can run it offline via `npm ci` plus npx.
 */
const fs = require('fs');
const os = require('os');
const path = require('path');
const openapiTS = require('openapi-typescript').default;
const astToString = require('openapi-typescript').astToString;

const ROOT = path.resolve(__dirname, '..');
const OPENAPI_DIR = path.resolve(ROOT, '..', 'openapi');

// Each entry maps an input spec to the committed client output file.
const SOURCES = [
  {
    input: path.join(OPENAPI_DIR, 'ewoh.yaml'),
    output: path.join(ROOT, 'client', 'src', 'types', 'openapi.d.ts'),
    header: '// Generated by scripts/gen-openapi.js from openapi/ewoh.yaml. DO NOT EDIT.',
  },
  {
    input: path.join(OPENAPI_DIR, 'work-orchestration.yaml'),
    output: path.join(ROOT, 'client', 'src', 'types', 'work-orchestration.d.ts'),
    header:
      '// Generated by scripts/gen-openapi.js from openapi/work-orchestration.yaml. DO NOT EDIT.',
  },
];

async function generateOne(source) {
  const schema = await fs.promises.readFile(source.input, 'utf8');
  const ast = await openapiTS(schema);
  const body = astToString(ast).trim();
  return `${source.header}\n\n${body}\n`;
}

async function generateAll(outDir) {
  for (const source of SOURCES) {
    const content = await generateOne(source);
    const outFile = path.join(outDir, path.relative(ROOT, source.output));
    fs.mkdirSync(path.dirname(outFile), { recursive: true });
    fs.writeFileSync(outFile, content);
  }
}

function filesEqual(a, b) {
  return fs.readFileSync(a, 'utf8') === fs.readFileSync(b, 'utf8');
}

async function main() {
  const check = process.argv.includes('--check');

  if (check) {
    const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'ewoh-openapi-check-'));
    const generated = path.join(tmp, 'gen');
    try {
      await generateAll(generated);
      let drift = false;
      for (const source of SOURCES) {
        const generatedFile = path.join(generated, path.relative(ROOT, source.output));
        if (!fs.existsSync(source.output)) {
          drift = true;
          console.error(`[drift] MISSING committed output: ${source.output}`);
          continue;
        }
        if (!filesEqual(generatedFile, source.output)) {
          drift = true;
          console.error(`[drift] STALE committed output: ${source.output}`);
        }
      }
      if (drift) {
        console.error(
          '\nERROR: generated OpenAPI contract drift detected.\n' +
            'Run `npm run gen:openapi` and commit the regenerated ' +
            'client/src/types/*.d.ts files.',
        );
        process.exit(1);
      }
      console.log('OK: OpenAPI contract checked; committed outputs are in sync.');
    } finally {
      fs.rmSync(tmp, { recursive: true, force: true });
    }
    return;
  }

  await generateAll(ROOT);
  for (const source of SOURCES) {
    console.log(`Generated ${path.relative(ROOT, source.output)}`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});